/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ComprarCriptomoedas;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 * A classe CotacoesCompraCripto é a janela que o investidor pode comprar a 
 * criptomoeda que deseja. Ela possui um metodo que seta os valores em uma area
 * de texto, possui um objeto da classe ComprarCriptomoedas, recebendo o metodo
 * que faz a compra das criptomoedas.
 *
 * @author João Pedro Sabino Garcia
 * @version 1.0
 */
public class CotacoesCompraCripto extends javax.swing.JFrame {

    /**
     * Creates new form CotacoesCompraCripto
     */
    public CotacoesCompraCripto(String cotacoes) {
        initComponents();
        comprarCripto = new ComprarCriptomoedas(this);
        txtMostraCotacoes.setText(cotacoes); 
    }

    public JButton getBtComprarCripto() {
        return btComprarCripto;
    }

    public void setBtComprarCripto(JButton btComprarCripto) {
        this.btComprarCripto = btComprarCripto;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JComboBox<String> getCbEscolhaCripto() {
        return cbEscolhaCripto;
    }

    public void setCbEscolhaCripto(JComboBox<String> cbEscolhaCripto) {
        this.cbEscolhaCripto = cbEscolhaCripto;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblDigiteValor() {
        return lblDigiteValor;
    }

    public void setLblDigiteValor(JLabel lblDigiteValor) {
        this.lblDigiteValor = lblDigiteValor;
    }

    public JLabel getLblEscolha() {
        return lblEscolha;
    }

    public void setLblEscolha(JLabel lblEscolha) {
        this.lblEscolha = lblEscolha;
    }

    public JLabel getLblTituloCotacoesCompra() {
        return lblTituloCotacoesCompra;
    }

    public void setLblTituloCotacoesCompra(JLabel lblTituloCotacoesCompra) {
        this.lblTituloCotacoesCompra = lblTituloCotacoesCompra;
    }

    public JTextArea getTxtMostraCotacoes() {
        return txtMostraCotacoes;
    }

    public void setTxtMostraCotacoes(JTextArea txtMostraCotacoes) {
        this.txtMostraCotacoes = txtMostraCotacoes;
    }

    public JTextField getTxtValorCompraCripto() {
        return txtValorCompraCripto;
    }

    public void setTxtValorCompraCripto(JTextField txtValorCompraCripto) {
        this.txtValorCompraCripto = txtValorCompraCripto;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTituloCotacoesCompra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostraCotacoes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cbEscolhaCripto = new javax.swing.JComboBox<>();
        lblEscolha = new javax.swing.JLabel();
        lblDigiteValor = new javax.swing.JLabel();
        txtValorCompraCripto = new javax.swing.JTextField();
        btComprarCripto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloCotacoesCompra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloCotacoesCompra.setText("COTAÇÕES CRIPTOMOEDAS");

        txtMostraCotacoes.setColumns(20);
        txtMostraCotacoes.setRows(5);
        txtMostraCotacoes.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMostraCotacoesInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(txtMostraCotacoes);

        cbEscolhaCripto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbEscolhaCripto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bitcoin", "Ethereum", "Ripple" }));
        cbEscolhaCripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaCriptoActionPerformed(evt);
            }
        });

        lblEscolha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEscolha.setText("Escolha qual Criptomoeda deseja comprar:");

        lblDigiteValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDigiteValor.setText("Digite quanto deseja comprar:");

        txtValorCompraCripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCompraCriptoActionPerformed(evt);
            }
        });

        btComprarCripto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btComprarCripto.setText("COMPRAR");
        btComprarCripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComprarCriptoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEscolha)
                        .addGap(31, 31, 31)
                        .addComponent(cbEscolhaCripto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDigiteValor)
                        .addGap(18, 18, 18)
                        .addComponent(txtValorCompraCripto, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTituloCotacoesCompra)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btComprarCripto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloCotacoesCompra)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEscolhaCripto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEscolha))
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDigiteValor)
                    .addComponent(txtValorCompraCripto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btComprarCripto)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEscolhaCriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaCriptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEscolhaCriptoActionPerformed

    private void btComprarCriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComprarCriptoActionPerformed
        comprarCripto.comprarCriptomoeda();
    }//GEN-LAST:event_btComprarCriptoActionPerformed

    private void txtValorCompraCriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCompraCriptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompraCriptoActionPerformed

    private void txtMostraCotacoesInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMostraCotacoesInputMethodTextChanged
        
    }//GEN-LAST:event_txtMostraCotacoesInputMethodTextChanged
    
    public void setCotacoes(String cotacoes) {
        txtMostraCotacoes.setText(cotacoes);
    }
    
    public String getCriptomoeda() {
        return (String) cbEscolhaCripto.getSelectedItem();
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CotacoesCompraCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CotacoesCompraCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CotacoesCompraCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CotacoesCompraCripto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CotacoesCompraCripto().setVisible(true);
//            }
//        });
//    }
    
    private ComprarCriptomoedas comprarCripto;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btComprarCripto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbEscolhaCripto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDigiteValor;
    private javax.swing.JLabel lblEscolha;
    private javax.swing.JLabel lblTituloCotacoesCompra;
    private javax.swing.JTextArea txtMostraCotacoes;
    private javax.swing.JTextField txtValorCompraCripto;
    // End of variables declaration//GEN-END:variables
}
