/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SaldoInvestidor;
import DAO.ConexaoBancoDados;
import DAO.InvestidorConectado;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.SQLException;

/**
 *
 * @author Jpsab
 */
public class Saldo extends javax.swing.JFrame {

    /**
     * Creates new form Saldo
     */
    public Saldo() {
        initComponents();
        inicializarComponentesDeNegocio();
        this.saldoInvestidor = saldoInvestidor;
    }

    public SaldoInvestidor getSaldoInvestidor() {
        return saldoInvestidor;
    }

    public void setSaldoInvestidor(SaldoInvestidor saldoInvestidor) {
        this.saldoInvestidor = saldoInvestidor;
    }

    public JButton getBtConsultarSaldo() {
        return btConsultarSaldo;
    }

    public void setBtConsultarSaldo(JButton btConsultarSaldo) {
        this.btConsultarSaldo = btConsultarSaldo;
    }

    public JLabel getLblSenhaSaldo() {
        return lblSenhaSaldo;
    }

    public void setLblSenhaSaldo(JLabel lblSenhaSaldo) {
        this.lblSenhaSaldo = lblSenhaSaldo;
    }

    public JLabel getLblTituloSaldo() {
        return lblTituloSaldo;
    }

    public void setLblTituloSaldo(JLabel lblTituloSaldo) {
        this.lblTituloSaldo = lblTituloSaldo;
    }

    public JTextField getTxtMostraSaldos() {
        return txtMostraSaldos;
    }

    public void setTxtMostraSaldos(JTextField txtMostraSaldos) {
        this.txtMostraSaldos = txtMostraSaldos;
    }

    public JTextField getTxtSenhaSaldo() {
        return txtSenhaSaldo;
    }

    public void setTxtSenhaSaldo(JTextField txtSenhaSaldo) {
        this.txtSenhaSaldo = txtSenhaSaldo;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloSaldo = new javax.swing.JLabel();
        txtSenhaSaldo = new javax.swing.JTextField();
        lblSenhaSaldo = new javax.swing.JLabel();
        btConsultarSaldo = new javax.swing.JButton();
        txtMostraSaldos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloSaldo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloSaldo.setText("SALDO");

        txtSenhaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaSaldoActionPerformed(evt);
            }
        });

        lblSenhaSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSenhaSaldo.setText("Digite sua senha para conferir seus saldos:");

        btConsultarSaldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btConsultarSaldo.setText("Consultar Saldo");
        btConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSaldoActionPerformed(evt);
            }
        });

        txtMostraSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMostraSaldosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblSenhaSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(txtSenhaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(lblTituloSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btConsultarSaldo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txtMostraSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTituloSaldo)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenhaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btConsultarSaldo)
                .addGap(27, 27, 27)
                .addComponent(txtMostraSaldos, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaSaldoActionPerformed
        
    }//GEN-LAST:event_txtSenhaSaldoActionPerformed
    
    private void inicializarComponentesDeNegocio() {
    try {
        ConexaoBancoDados conexao = new ConexaoBancoDados();
        InvestidorConectado investidorConectado = new InvestidorConectado(conexao.getConnection());
        // Suponha que você tem uma forma de obter o investidorId aqui
        String investidorId = "id do investidor"; // Você deve substituir isso pelo ID real obtido após o login
        this.saldoInvestidor = new SaldoInvestidor(investidorConectado, investidorId);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao iniciar a conexão: " + e.getMessage());
    }
    } 
    private void btConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSaldoActionPerformed
       String senha = txtSenhaSaldo.getText();
        if (saldoInvestidor != null) {
            String resultado = saldoInvestidor.verificarSenhaEObterSaldos(senha);
            if (!resultado.equals("Senha incorreta")) {
                txtMostraSaldos.setText(resultado);
            } else {
                JOptionPane.showMessageDialog(this, "Senha incorreta, tente novamente.");
                txtSenhaSaldo.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistema não inicializado corretamente.");
        }
    }//GEN-LAST:event_btConsultarSaldoActionPerformed

    private void txtMostraSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMostraSaldosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMostraSaldosActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saldo().setVisible(true);
            }
        });
    }
    
    private SaldoInvestidor saldoInvestidor; 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarSaldo;
    private javax.swing.JLabel lblSenhaSaldo;
    private javax.swing.JLabel lblTituloSaldo;
    private javax.swing.JTextField txtMostraSaldos;
    private javax.swing.JTextField txtSenhaSaldo;
    // End of variables declaration//GEN-END:variables
}
